name: notebook
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  appflowy_editor: ^1.4.4
  awesome_notifications: ^0.8.2
  cupertino_icons: ^1.0.6
  dynamic_color: ^1.6.8
  filesystem_picker: ^3.1.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_keyboard_visibility: ^5.4.1
  flutter_localization: ^0.1.14
  flutter_mobx: ^2.1.0
  flutter_staggered_grid_view: ^0.7.0
  get_it: ^7.6.4
  html: ^0.15.4
  image_picker: ^1.0.4
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  keyboard_attachable: ^2.1.0
  local_auth: ^2.1.7
  logger: ^2.0.2+1
  markdown: ^7.1.1
  mobx: ^2.2.0
  package_info: ^2.0.2
  path: ^1.8.3
  path_provider: ^2.1.1
  pdf: ^3.10.4
  permission_handler: ^11.0.1
  printing: ^5.11.0
  share_plus: ^7.2.1
  shared_preferences: ^2.2.1
  shimmer: ^3.0.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  rename: ^3.0.0
  mobx_codegen: ^2.4.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "lib/resources/icons/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  
  assets:     
        - lib/resources/
        - lib/resources/icons/
        - lib/resources/images/
        - lib/resources/icons/pin.png

  fonts:
    - family: Inter
      fonts:
        - asset: lib/resources/fonts/Inter-Thin.ttf
          weight: 100
        - asset: lib/resources/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: lib/resources/fonts/Inter-Light.ttf
          weight: 300
        - asset: lib/resources/fonts/Inter-Regular.ttf
          weight: 400
        - asset: lib/resources/fonts/Inter-Medium.ttf
          weight: 500
        - asset: lib/resources/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: lib/resources/fonts/Inter-Bold.ttf
          weight: 700
        - asset: lib/resources/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: lib/resources/fonts/Inter-Black.ttf
          weight: 900
    - family: SourceCodePro
      fonts:
        - asset: lib/resources/fonts/SourceCodePro-Regular.ttf
          weight: 400